import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Sanjeev Midda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>

      <div className="App">
        <div className="links">
          <h4>SANJEEV MIDDA</h4>
          <h4>/1 - about</h4>
          <h4>/2 - locations</h4>
          <h4>/3 - philosophy</h4>
        </div>
        <div className="pageContainer">
          <div className="circle"></div>
        </div>
      </div>
        
    </>
  )
}
